"""empty message

Revision ID: 48a0541a348e
Revises: 
Create Date: 2025-01-06 20:28:15.533732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a0541a348e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_assets',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('laptop', sa.String(length=100), nullable=False),
    sa.Column('monitor', sa.String(length=100), nullable=False),
    sa.Column('wired_keyboard', sa.String(length=100), nullable=False),
    sa.Column('wired_mouse', sa.String(length=100), nullable=False),
    sa.Column('wireless_mouse', sa.String(length=100), nullable=False),
    sa.Column('airtel_dongle', sa.String(length=100), nullable=False),
    sa.Column('id_card', sa.String(length=100), nullable=False),
    sa.Column('employment_status', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('joining',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('employee_address', sa.String(length=255), nullable=True),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('business_title', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('reporting_manager', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('requirements',
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('business_unit', sa.String(length=100), nullable=True),
    sa.Column('resource_requirement', sa.String(length=100), nullable=True),
    sa.Column('job_description', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('business_title', sa.String(length=100), nullable=True),
    sa.Column('vector_title', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('interview_status',
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('interview_status', sa.String(length=50), nullable=True),
    sa.Column('interview_round', sa.String(length=50), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.requirement_id'], ),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('requirement_approval',
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.requirement_id'], ),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('software_licenses',
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['joining.employee_id'], ),
    sa.PrimaryKeyConstraint('license_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('license_attributes',
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=True),
    sa.Column('attribute_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['software_licenses.license_id'], ),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('license_attributes')
    op.drop_table('users')
    op.drop_table('software_licenses')
    op.drop_table('requirement_approval')
    op.drop_table('interview_status')
    op.drop_table('roles')
    op.drop_table('requirements')
    op.drop_table('joining')
    op.drop_table('it_assets')
    # ### end Alembic commands ###
