"""empty message

Revision ID: ff5c69f54da9
Revises: a019bac2609b
Create Date: 2025-01-09 01:19:58.075576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5c69f54da9'
down_revision = 'a019bac2609b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joining', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emp_email_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joining', schema=None) as batch_op:
        batch_op.drop_column('emp_email_id')

    # ### end Alembic commands ###
