"""empty message

Revision ID: 09fe17a6cc45
Revises: beab935900a9
Create Date: 2025-01-10 02:59:22.218428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fe17a6cc45'
down_revision = 'beab935900a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_status', schema=None) as batch_op:
        batch_op.drop_column('interview_id')

    # ### end Alembic commands ###
