"""empty message

Revision ID: 560c9751dc56
Revises: 09fe17a6cc45
Create Date: 2025-01-10 21:59:07.073128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560c9751dc56'
down_revision = '09fe17a6cc45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_id', sa.Integer(), autoincrement=True, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_approval', schema=None) as batch_op:
        batch_op.drop_column('approval_id')

    # ### end Alembic commands ###
