"""empty message

Revision ID: beab935900a9
Revises: 48a0541a348e
Create Date: 2025-01-09 04:03:24.361411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beab935900a9'
down_revision = '48a0541a348e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joining', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emp_email_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('job_description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.alter_column('job_description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('joining', schema=None) as batch_op:
        batch_op.drop_column('emp_email_id')

    # ### end Alembic commands ###
